# Generated by Django 4.2.3 on 2023-08-21 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='gradpage/images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Display_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('address', models.TextField(max_length=100)),
                ('date', models.DateField()),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to='gradpage/images/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('require_for_grad', models.TextField()),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gradpage.archive')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradpage.department')),
                ('display_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gradpage.display_info')),
            ],
        ),
    ]
